name: quero_workar
description: Quero Workar Mobile.
version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  html: ^0.14.0+3
  flutter_html: ^0.11.1
  transparent_image: ^1.0.0
  loading: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
